---
title: "comparison"
format: html
editor: visual
self-contained: true
---

Load in libraries and data

```{r, message = FALSE, warning = FALSE, echo = F}

knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = F)
source("R/functions.R")
source("R/libraries.R")
source("R/t_test_results.R")
source("R/limma_results.R")

load(here::here('data/se.rda'))
load(here::here('data/metadata.rda'))
load(here::here('data/df_long.rda'))
load(here::here('data/df_long_summary.rda'))
load(here::here('data/df_long_av_difference.rda'))
load(here::here('data/df_long_av_difference_summary.rda'))

```

# Volcanoes adjusted

```{r}
all_results <- rbind(results_one_sample_pre, results_one_sample_baseline, results_one_sample_exercise, results_one_sample_rec60, results_one_sample_rec180)

all_results%>%
    mutate(color = case_when(
        logFC >= 0 & q <= 0.05 ~ "Uptake",
        logFC <= 0 & q < 0.05 ~ "Release",
        TRUE ~ "Unchanged")) %>%
    ggplot(aes(x=logFC, y=-log10(P.Value), label = metabolite))+
    geom_point(aes(color = color), size = 2)+
    theme(panel.background = element_blank(),
          panel.border = element_rect(colour = "black", fill=NA),
          panel.grid.minor=element_blank(),
          panel.grid.major = element_blank(),
          plot.background = element_rect(color = "white"),
          plot.title = element_text(size=8),
          axis.line = element_blank(),
          text = element_text(size = 8, family="Source Sans Pro"),
          legend.title = element_blank(),
          legend.key = element_blank(),
          strip.background = element_blank(),
          legend.position = "none"
    )+
    geom_text_repel(point.size=2, size=1, min.segment.length = Inf, force=0.3)+
    scale_color_manual(breaks = c("Uptake", "Release", "Unchanged"),
                       values=c("dodgerblue3", "firebrick3", "gray50"))+
    xlab("Log2fold change") + ylab("-log10(p)")+
    facet_grid(~factor(time, levels=c('pre', 'baseline', 'exercise', 'rec60', 'rec180')))

ggplot2::ggsave(here::here('data/figures/comparison/volcanoes_with_flow.svg'), height=45, width=135, units = "mm")
```

# Number of uptake and release peptides, adjusted

```{r}
#Need to collect all result sheets into one sheet
df_long_av_difference_summary %>% 
    merge(all_results[,c("time", "metabolite", "q")], by=c("time", "metabolite")) %>% #Merge the "regulated" column into results_combined
    dplyr::filter(q < 0.05) %>% #Filter for only significant metabolites
    dplyr::mutate(direction = ifelse(mean > 0, "Uptake", "Release")) %>% #Creates a new column for color coding the plot
    dplyr::mutate(mean = abs(mean)) %>% #Makes all values positive
    dplyr::mutate(time = factor(time, levels = c("pre", "baseline", "exercise", "rec60", "rec180"))) %>% 
    dplyr::filter(!mean == 0) %>% 
    ggplot2::ggplot(aes(x=time, fill=direction))+
    geom_bar(aes(y = ..count..), stat = "count", position = "dodge")+
    theme(
        panel.background = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA),
        panel.grid.minor=element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_rect(fill = "white"),
        axis.line = element_blank(),
        text = element_text(size = 8, family="Source Sans Pro"),
        axis.title = element_text(size = 8, family="Source Sans Pro"),
        legend.title = element_blank(),
        legend.key = element_blank(),
        legend.key.size = (unit(3, "mm")),
        legend.position = c(0.05, 0.95), 
        legend.justification = c(0, 1), 
        legend.box.just = "left", 
        legend.margin = margin(0, 0, 0, 0),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        title = element_text(size = 6)
        )+
    scale_fill_manual(breaks = c("Release", "Uptake"),
                           values=c("#627282", "#b19f91"))+
    labs(y="Number of metabolites", x="")+
    ggtitle("Significant metabolites")

ggplot2::ggsave(here::here('data/figures/comparison/numbers.svg'), height=45, width=55, units = "mm")
```

# Volcanoes av

```{r}
all_results <- rbind(results_pre, results_baseline, results_exercise, results_rec60, results_rec180)

all_results%>%
    mutate(color = case_when(
        logFC >= 0 & q <= 0.05 ~ "Uptake",
        logFC <= 0 & q < 0.05 ~ "Release",
        TRUE ~ "Unchanged")) %>%
    ggplot(aes(x=logFC, y=-log10(P.Value), label = metabolite))+
    geom_point(aes(color = color), size = 2)+
    theme(panel.background = element_blank(),
          panel.border = element_rect(colour = "black", fill=NA),
          panel.grid.minor=element_blank(),
          panel.grid.major = element_blank(),
          plot.background = element_rect(color = "white"),
          plot.title = element_text(size=8),
          axis.line = element_blank(),
          text = element_text(size = 8, family="Source Sans Pro"),
          legend.title = element_blank(),
          legend.key = element_blank(),
          strip.background = element_blank(),
          legend.position = "none"
    )+
    geom_text_repel(point.size=2, size=1, min.segment.length = Inf, force=0.3)+
    scale_color_manual(breaks = c("Uptake", "Release", "Unchanged"),
                       values=c("dodgerblue3", "firebrick3", "gray50"))+
    xlab("Log2fold change") + ylab("-log10(p)")+
    facet_grid(~factor(time, levels=c('pre', 'baseline', 'exercise', 'rec60', 'rec180')))

ggplot2::ggsave(here::here('data/figures/comparison/volcanoes_av.svg'), height=45, width=135, units = "mm")
```

# Number of uptake and release metabolites, av

```{r}
#Need to collect all result sheets into one sheet
df_long_av_difference_summary %>% 
    merge(all_results[,c("time", "metabolite", "q")], by=c("time", "metabolite")) %>% #Merge the "regulated" column into results_combined
    dplyr::filter(q < 0.05) %>% #Filter for only significant metabolites
    dplyr::mutate(direction = ifelse(mean > 0, "Uptake", "Release")) %>% #Creates a new column for color coding the plot
    dplyr::mutate(mean = abs(mean)) %>% #Makes all values positive
    dplyr::mutate(time = factor(time, levels = c("pre", "baseline", "exercise", "rec60", "rec180"))) %>% 
    dplyr::filter(!mean == 0) %>% 
    ggplot2::ggplot(aes(x=time, fill=direction))+
    geom_bar(aes(y = ..count..), stat = "count", position = "dodge")+
    theme(
        panel.background = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA),
        panel.grid.minor=element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_rect(fill = "white"),
        axis.line = element_blank(),
        text = element_text(size = 8, family="Source Sans Pro"),
        axis.title = element_text(size = 8, family="Source Sans Pro"),
        legend.title = element_blank(),
        legend.key = element_blank(),
        legend.key.size = (unit(3, "mm")),
        legend.position = c(0.05, 0.95), 
        legend.justification = c(0, 1), 
        legend.box.just = "left", 
        legend.margin = margin(0, 0, 0, 0),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        title = element_text(size = 6)
        )+
    scale_fill_manual(breaks = c("Release", "Uptake"),
                           values=c("#627282", "#b19f91"))+
    labs(y="Number of metabolites", x="")+
    ggtitle("Significant metabolites")

ggplot2::ggsave(here::here('data/figures/comparison/numbers_av.svg'), height=45, width=55, units = "mm")
```
